channels:
  - defaults
  - conda-forge
dependencies:
  # Core
  - python>=3.8
  - pip>=21
  # Data Science
  - matplotlib
  # Learning
  - scikit-learn
  - nltk
  - bs4
  - pip:
    # Learning
    - keras
    - tensorflow
    - tensorflow-gpu
    # Visual
    - streamlit
    # Dependencies
    - opencv-python